[package]
name = "ex1"
version = "0.1.0"
edition = "2021"

[dependencies]
layer-config = { path = "../../" }

clap = { version = "4.4.7", features = ["derive"] }
serde = { version = "1.0.190", features = ["derive"] }
serde_yaml = "0.9.27"
eyre = "0.6.8"
