[package]
name = "ex1"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
layer_config = { path = "../../layer_config" }
serde = { version = "1.0.192", features = ["derive"] }
serde_yaml = "0.9.27"
